# How many volleys of spawning should occur?
amount-of-volleys: 20
# What is the delay between each volley?
interval-between-volley: 500
# How many times should danger (fireball or lightning) be spawned each volley?
iterations-per-volley: 5
# Velocity of fireballs in the Y direction downward
# Caution: Setting to a value 4 or above can cause excessive velocity warnings
fireball-velocity: 1.5
# Whether to use small fireballs
small-fireballs: false
# Warning message sent to players inside the radius + buffer
warning-message: '&cWarning: The area around %X%, %Z% will be nuked soon.'
# Players who are less than radius + buffer blocks from the target will be warned
warning-buffer: 20
# How long do players have to clear out of the area before danger starts spawning?
warning-time-seconds: 5
# What is the maximum radius?
radius-limit: 64
commands:
  world-not-exist: '&e%WORLD% &cdoes not exist.'
  no-permission: '&cSorry, you cannot use this.'
  usage: '&cUsage: /nuke &e<x> <z> <radius> [world]'
  not-a-number: '&e%INPUT% &c is not a number'
  too-large-radius: '&e%RADIUS%&c is too large'
  negative-radius: '&cCannot specify a negative radius.'
  success-message: '&7Nuking &e%X%, %Z%...'
config-version: 3